name: Protect secrets
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .env exists
        run: |
          if [ -f ".env" ] || git ls-files | grep -E '(^|/)\.env$'; then
            echo "::error::.env found in repository. Remove it before pushing."
            exit 1
          fi
          echo "OK: no .env tracked."
